# Generated by Django 6.0.2 on 2026-02-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaos', '0002_alter_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(default='student', max_length=50),
        ),
    ]
